from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any


class ActionV2(ABC):
    @abstractmethod
    def reset_subject(self) -> None: ...
    @abstractmethod
    def adapt_on_context(self, context: Any) -> None: ...
    @abstractmethod
    def predict_context(self, context: Any) -> Any: ...
    @abstractmethod
    def freeze_state(self) -> Any: ...
    @abstractmethod
    def predict_future(self, future: Any) -> Any: ...
    @abstractmethod
    def state_hash(self) -> str: ...
    @abstractmethod
    def diagnostics(self) -> dict[str, object]: ...
    @abstractmethod
    def failure_status(self) -> str: ...
